package barokah_atk;

import admin.adm_dashboard;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import fungsi_lain.session;
import kasir.ksr_dashboard;
import fungsi_lain.RoundedPanel;
import fungsi_tambah_data.FormTambah;
import jakarta.mail.*;
import jakarta.mail.internet.*;
import java.awt.Frame;
import java.util.Properties;

public class ResetSandi extends javax.swing.JFrame {

    private PreparedStatement stat;
    private ResultSet rs;
    private String idKaryawan = "";
    private String email = "";
    private String kode = "";
    private boolean isPaswordEdit = false;

    konek k = new konek();

    public ResetSandi() {
        k.connect();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void sendVerificationCode(String toEmail, String code) {
        final String fromEmail = "tokobarokahatk5@gmail.com";
        final String password = "dlkk sdtj tqjf uqxt"; // gunakan App Password jika pakai Gmail

        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");

        Session session = Session.getInstance(props, new jakarta.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, password);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(fromEmail));
            message.setRecipients(
                    Message.RecipientType.TO,
                    InternetAddress.parse(toEmail)
            );
            message.setSubject("Kode Verifikasi Anda");
            message.setText("Kode verifikasi Anda adalah: " + code);

            Transport.send(message);
            JOptionPane.showMessageDialog(null, "Kode Verifikasi sudah dikirim! harap cek email anda");
            popUp();
        } catch (MessagingException e) {
            e.printStackTrace();
        }
    }

    private void popUp() {
        FormKodeVerifikasi form = new FormKodeVerifikasi(this);
        if (form.showDialog()) {
            JOptionPane.showMessageDialog(null, "verifikasi berhasil! silahkan masukkan password baru");
            txt_email.setEnabled(false);
            txt_password.setEnabled(true);
            isPaswordEdit = true;
            txt_password.requestFocusInWindow();
        }
    }

    private void cekEmail() {
        try {
            this.stat = k.getCon().prepareStatement("SELECT id_karyawan, email from karyawan where email = ?");
            stat.setString(1, txt_email.getText());
            this.rs = this.stat.executeQuery();
            if (rs.next()) {
                String id = rs.getString("id_karyawan");
                String eml = rs.getString("email");
                this.idKaryawan = id;
                this.email = eml;
                kirimEmail();
            } else {
                JOptionPane.showMessageDialog(null, "Email tidak terdaftar! harap masukkan email anda yang sudah terdaftar sebelumnya");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void kirimEmail() {
        int code = (int) (Math.random() * 900000) + 100000; // hasilnya antara 100000 - 999999
        String kodeVerifikasi = String.valueOf(code);
        this.kode = kodeVerifikasi;
        System.out.println("kode : " + kode);
        sendVerificationCode(email, kodeVerifikasi);
    }

    class FormKodeVerifikasi extends FormTambah {

        public FormKodeVerifikasi(Frame parent) {
            super(parent, "Verifikasi", "Masukkan Kode Verifikasi");
        }

        @Override
        protected boolean validateInput() {
            String input = fieldMap.get("Masukkan Kode Verifikasi").getText();
            if (!input.equals(kode)) {
                setPesan("kode verifikasi salah!");
                return false;
            }
            if (!input.matches("\\d+")) {
                setPesan("Masukkan hanya angka!");
                return false;
            }
            return true;
        }

        @Override
        protected boolean isDuplicate(String column, String value) {
            //    
            return false;
            //    
        }

    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelj = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(30);
        txt_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        showpasswd = new javax.swing.JCheckBox();
        btn_submit = new javax.swing.JLabel();
        btn_lupaSandi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelj1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(17, 45, 78));
        jPanel2.setForeground(new java.awt.Color(54, 116, 181));
        jPanel2.setPreferredSize(new java.awt.Dimension(550, 700));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo buatan affan 1.png"))); // NOI18N

        labelj.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelj.setForeground(new java.awt.Color(204, 204, 204));
        labelj.setText("BAROKAH ATK");

        jPanel3.setBackground(new java.awt.Color(219, 226, 239));

        txt_email.setBackground(new java.awt.Color(242, 232, 198));
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(17, 45, 78));
        jLabel6.setText("Email");

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(17, 45, 78));
        jLabel7.setText("Password Baru");

        txt_password.setBackground(new java.awt.Color(242, 232, 198));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_password.setEnabled(false);
        txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwordMouseClicked(evt);
            }
        });
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        showpasswd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showpasswd.setForeground(new java.awt.Color(17, 45, 78));
        showpasswd.setText("Show Password");
        showpasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswdActionPerformed(evt);
            }
        });

        btn_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/submit panjang2.png"))); // NOI18N
        btn_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
        });

        btn_lupaSandi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_lupaSandi.setForeground(new java.awt.Color(0, 51, 102));
        btn_lupaSandi.setText("<< Kembali Ke Halaman Login");
        btn_lupaSandi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_lupaSandi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lupaSandiMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_lupaSandiMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(50, 50, 50));
        jLabel4.setText("Masukkan Email anda yang sudah terdaftar");

        labelj1.setBackground(new java.awt.Color(17, 45, 78));
        labelj1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelj1.setForeground(new java.awt.Color(17, 45, 78));
        labelj1.setText("Lupa Sandi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(50, 50, 50));
        jLabel5.setText("________________________________________________________________________");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showpasswd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_lupaSandi)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_submit)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                        .addComponent(txt_email)))))))
                .addGap(46, 46, 46))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(labelj1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(148, 148, 148))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelj1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showpasswd)
                .addGap(34, 34, 34)
                .addComponent(btn_submit)
                .addGap(18, 18, 18)
                .addComponent(btn_lupaSandi)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(labelj)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labelj))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
        if (!isPaswordEdit) {
            if (txt_email.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "harap masukkan email!");
            } else {
                cekEmail();
            }
        } else {
            JOptionPane.showMessageDialog(null, "anjayy");
        }
    }//GEN-LAST:event_btn_submitMouseClicked

    private void btn_lupaSandiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lupaSandiMouseClicked
        // TODO add your handling code here:
        Login a = new Login();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_lupaSandiMouseClicked

    private void txt_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordMouseClicked

    private void showpasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswdActionPerformed
        // TODO add your handling code here:
        if (showpasswd.isSelected()) {
            txt_password.setEchoChar((char) 0);

        } else {
            txt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_showpasswdActionPerformed

    private void btn_lupaSandiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lupaSandiMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lupaSandiMouseReleased

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        UIManager.put("Panel.background", new Color(128, 0, 0));
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetSandi().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_lupaSandi;
    private javax.swing.JLabel btn_submit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelj;
    private javax.swing.JLabel labelj1;
    private javax.swing.JCheckBox showpasswd;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
